// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVv98Ufdl1xcX89DGX9H1bOHveSr0FPZ0',
    appId: '1:133198022632:web:0f66608fe8ab2559a2065d',
    messagingSenderId: '133198022632',
    projectId: 'alien-resume-x',
    authDomain: 'alien-resume-x.firebaseapp.com',
    storageBucket: 'alien-resume-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBns4HGlvwsUe-neiiZdOM25IxRImgoq-s',
    appId: '1:133198022632:android:6cc5e1b77beab934a2065d',
    messagingSenderId: '133198022632',
    projectId: 'alien-resume-x',
    storageBucket: 'alien-resume-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmD-sanOgFs_JJL8Z0wbvQsNidRCC_KtI',
    appId: '1:133198022632:ios:a64589fe076d9ec9a2065d',
    messagingSenderId: '133198022632',
    projectId: 'alien-resume-x',
    storageBucket: 'alien-resume-x.appspot.com',
    iosClientId: '133198022632-af0n8pqt36kccn2cv6ta85rscjnrbhc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumex',
  );
}
